[target.aarch64-apple-darwin]
rustflags = ["-Ctarget-cpu=native"]
rustdocflags = ["-Ctarget-cpu=native"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Ctarget-feature=+vaes,+avx512f"]
rustdocflags = ["-Ctarget-feature=+vaes,+avx512f"]
